version: "3.4"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: db_imi_test
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: db_imi_test
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - "${GITHUB_WORKSPACE}:/imi"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d db_imi_test" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  redis:
    image: redis:6
    container_name: redis
    volumes:
      - ./redis.conf:/etc/redis.conf
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "4369:4369"
      - "15672:15672"
      - "5672:5672"
      - "25672:25672"
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc -w 2 -zv 127.0.0.1 2181" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  kafka1:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HOST_NAME: kafka1
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: hostname -i
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS:
        queue-imi-1:3:1
        QueueTest1:3:1
        imi-kafka-queue-test:3:1
    ports:
      - "9092:9092"