[framework]
name = "imi"

[swoole]
dockerfile = "imi-swoole.dockerfile"
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/dbModel"
urls.query = "/queryModel?queries="
urls.update = "/updateModel?queries="
urls.fortune = "/fortunes"
urls.cached_query = "/cached-worlds?count="
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "Swoole"
webserver = "None"
versus = "Swoole"

[swoole-db-raw]
dockerfile = "imi-swoole.dockerfile"
urls.db = "/dbRaw"
urls.query = "/queryRaw?queries="
urls.update = "/updateRaw?queries="
urls.fortune = "/fortunesRaw"
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Swoole"
webserver = "None"
versus = "Swoole"


[workerman]
dockerfile = "imi-workerman.dockerfile"
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/dbModel"
urls.query = "/queryModel?queries="
urls.update = "/updateModel?queries="
urls.fortune = "/fortunes"
urls.cached_query = "/cached-worlds?count="
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "Workerman"
webserver = "None"
versus = "Workerman"

[workerman-db-raw]
dockerfile = "imi-workerman.dockerfile"
urls.db = "/dbRaw"
urls.query = "/queryRaw?queries="
urls.update = "/updateRaw?queries="
urls.fortune = "/fortunesRaw"
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Workerman"
webserver = "None"
versus = "Workerman"

