name: Test

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Redis Server
        run: |
          nuget install redis-64 -excludeversion
          redis-64\tools\redis-server.exe --service-install
          redis-64\tools\redis-server.exe --service-start
          '@ECHO Redis Started'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          ini-values: session.save_path=C:\temp
          tools: pecl
          extensions: bcmath, curl, openssl, mbstring, intl, json, igbinary, redis, mysqli, pdo, pdo_mysql
      
      - name: Test
        run: |
          php -v
          php -m
          composer -V
          php test2.php
          php -r "sleep(5);"
          php -r "echo file_get_contents('cli.log');"