name: Test

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          ini-values: apc.enable_cli=on, session.save_path=C:\temp
          tools: pecl
          extensions: mbstring, intl, json, yaml, apcu, imagick, gd, gettext, igbinary, sqlite3, msgpack, psr, redis, mysqli, pdo, pdo_mysql

      - name: Test
        run: |
          php -v
          php -m
          composer -V
