name: Test

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          ini-values: session.save_path=C:\temp
          tools: pecl
          extensions: bcmath, curl, openssl, mbstring, intl, json, igbinary, redis, mysqli, pdo, pdo_mysql

      - name: Test
        run: |
          php -v
          php -m
          composer -V
          bin\test.ps1
          php -r "sleep(3);"
          php -r "echo file_get_contents('cli.log');"